targets:
  $default:
    builders:
      vialer_generators:colorsGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/presentation/resources/theme/colors.dart

builders:
  colorsGeneratorBuilder:
    import: 'package:vialer_generators/generators.dart'
    builder_factories: ['colorsGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".vialer.dart"]}
    build_to: source