name: vialer_generators
description: A nested package containing all code generation used by Vialer.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  source_gen: ^1.4.0
  build: any
  analyzer: any
