#!/usr/bin/env bash
LC_ALL=C

printf "Running 'dart format'\n"
files=$(find . \
\( -name '*.dart' ! -name '*.i18n.dart' ! -name '*.g.dart' ! -name '*.chopper.dart' \) -print0 \
 | xargs -0)

if ! dart format -o none --fix --set-exit-if-changed $files
then
  printf "The above files need to be formatted.\n"
  exit 1
fi

printf "Running 'dart analyze'\n"
if ! dart analyze; then
  printf "Error running 'dart analyze'\n"
  exit 1
fi
printf "Finished running 'dart analyze'\n"

exit 0
