#!/usr/bin/env bash
LC_ALL=C

printf "Running 'dartfmt'\n"
changed_files=$(dartfmt . --set-exit-if-changed --fix -n)
if [ $? -ne 0 ]; then
  printf "The following files aren't formatted:\n"
  printf "%s\n" "$changed_files"
  exit 1
fi

printf "Running 'flutter analyze'\n"
flutter analyze
if [ $? -ne 0 ]; then
  printf "Error running 'flutter analyze'\n"
  exit 1
fi
printf "Finished running 'flutter analyze'\n"

exit 0
