#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^[0-9]+\-[a-z\-]+$"

message="Your commit will be rejected. You should rename your branch to a valid name (e.g.: 123-short-description) and try again.\n\nRename your branch by:\tgit branch -m 123-new-name\n"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    printf "$message"
    exit 1
fi

exit 0
