phrase:
  project_id: 32969223b3aa8d2c99ba865c611a15e5
  pull:
    targets:
    - file: ./lib/presentation/resources/messages.i18n.yaml
      params:
        locale_id: 85e4ba11caa8d4fe1e77f4452ae42b7e
        file_format: yml_symfony2
    - file: ./lib/presentation/resources/messages_nl.i18n.yaml
      params:
        locale_id: 0499f0d1de5f27e4b303f006f2ed912e
        file_format: yml_symfony2
    - file: ./lib/presentation/resources/messages_de.i18n.yaml
      params:
        locale_id: 8d203025039e93dda4d4a8eed1873ea9
        file_format: yml_symfony2
    - file: ./lib/presentation/resources/messages_fr.i18n.yaml
      params:
        locale_id: 54739e72c4121979414115078a2a1826
        file_format: yml_symfony2
