# For a list of available Phrase options, follow this link: https://www.rubydoc.info/gems/phraseapp-ruby/PhraseApp/RequestParams/LocaleDownloadParams
# Provided here because these are not well documented by Phrase.

phrase:
  project_id: 32969223b3aa8d2c99ba865c611a15e5
  pull:
    targets:
    - file: ./lib/presentation/resources/messages.i18n.yaml
      params:
        locale_id: 85e4ba11caa8d4fe1e77f4452ae42b7e
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
    - file: ./lib/presentation/resources/messages_nl.i18n.yaml
      params:
        locale_id: 0499f0d1de5f27e4b303f006f2ed912e
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
    - file: ./lib/presentation/resources/messages_de.i18n.yaml
      params:
        locale_id: 8d203025039e93dda4d4a8eed1873ea9
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
    - file: ./lib/presentation/resources/messages_fr.i18n.yaml
      params:
        locale_id: 54739e72c4121979414115078a2a1826
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
    - file: ./lib/presentation/resources/messages_es.i18n.yaml
      params:
        locale_id: 0e634e9d237c2de46b23a76d77005b7b
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
    - file: ./lib/presentation/resources/messages_pt.i18n.yaml
      params:
        locale_id: c0bb879bbc867e4a6960ea8602f7dae4
        file_format: yml_symfony2
        include_unverified_translations: true
        include_empty_translations: true
