include: package:effective_dart/analysis_options.1.2.0.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    type_annotate_public_apis: false
    prefer_mixin: false

    annotate_overrides: true
    omit_local_variable_types: true
    prefer_single_quotes: true
    use_function_type_syntax_for_parameters: true
    prefer_const_constructors: true
    avoid_print: true

analyzer:
  errors:
    missing_required_param: error
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
  exclude:
    - lib/**.i18n.dart
    - lib/**.chopper.dart
    - lib/**.g.dart
    - lib/app/util/pigeon.dart
    - lib/**.freezed.dart