include: package:austerity/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    type_annotate_public_apis: false
    prefer_mixin: false
    always_use_package_imports: false
    prefer_expression_function_bodies: false
    diagnostic_describe_all_properties: false
    avoid_annotating_with_dynamic: false
    # With Flutter, this can cause some dropped frames (although rarely).
    # See the following links:
    # - https://github.com/dart-lang/sdk/issues/36269
    # - https://gist.github.com/lukepighetti/921f347d94c889bc7febf59971892f10
    avoid_slow_async_io: false
    do_not_use_environment: false
    sort_pub_dependencies: false
    require_trailing_commas: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  strong-mode:
    implicit-dynamic: true
  exclude:
    - lib/**.i18n.dart
    - lib/**.chopper.dart
    - lib/**.g.dart
    - lib/presentation/util/pigeon.dart
    - lib/**.freezed.dart
    - test/**.mocks.dart