# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  source 'https://github.com/CocoaPods/Specs.git'

  pod 'le', :git => 'https://github.com/LogentriesCommunity/le_ios.git'
  pod 'Alamofire', '~> 5.4'
  pod 'Analytics', '~> 4.1'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # Existing build settings
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

          ## dart: PermissionGroup.calendar
          'PERMISSION_EVENTS=0',

          ## dart: PermissionGroup.reminders
          'PERMISSION_REMINDERS=0',

          ## dart: PermissionGroup.contacts
          'PERMISSION_CONTACTS=1',

          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=0',

          ## dart: PermissionGroup.microphone
          'PERMISSION_MICROPHONE=1',

          ## dart: PermissionGroup.speech
          'PERMISSION_SPEECH_RECOGNIZER=0',

          ## dart: PermissionGroup.photos
          'PERMISSION_PHOTOS=0',

          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          'PERMISSION_LOCATION=0',

          ## dart: PermissionGroup.notification
          'PERMISSION_NOTIFICATIONS=1',

          ## dart: PermissionGroup.mediaLibrary
          'PERMISSION_MEDIA_LIBRARY=0',

          ## dart: PermissionGroup.sensors
          'PERMISSION_SENSORS=0',

          ## dart: PermissionGroup.bluetooth
          'PERMISSION_BLUETOOTH=1',

          ## dart: PermissionGroup.appTrackingTransparency
          'PERMISSION_APP_TRACKING_TRANSPARENCY=0',

          ## dart: PermissionGroup.criticalAlerts
          'PERMISSION_CRITICAL_ALERTS=0',
      ]
    end
  end

  # CI-related clean-up
  if ENV['CI'] == 'true'
    Dir.glob("Pods/*").each do |pod_dir|
      privacy_files = Dir.glob("#{pod_dir}/**/PrivacyInfo.xcprivacy")
      privacy_files.each do |privacy_file|
        File.delete(privacy_file)
        puts "Deleted #{privacy_file}"
      end
    end
  end

  # Bitcode stripping
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  framework_paths = [
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox-ios.xcframework/ios-arm64/bctoolbox-ios.framework/bctoolbox-ios",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox-ios.xcframework/ios-arm64_x86_64-simulator/bctoolbox-ios.framework/bctoolbox-ios",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/bctoolbox-ios.xcframework/ios-arm64/bctoolbox-ios.framework/bctoolbox-ios",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/bctoolbox-ios.xcframework/ios-arm64_x86_64-simulator/bctoolbox-ios.framework/bctoolbox-ios",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox-tester.xcframework/ios-arm64/bctoolbox-tester.framework/bctoolbox-tester",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox-tester.xcframework/ios-arm64_x86_64-simulator/bctoolbox-tester.framework/bctoolbox-tester",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox.xcframework/ios-arm64/bctoolbox.framework/bctoolbox",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/bctoolbox.xcframework/ios-arm64_x86_64-simulator/bctoolbox.framework/bctoolbox",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/bctoolbox.xcframework/ios-arm64/bctoolbox.framework/bctoolbox",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/bctoolbox.xcframework/ios-arm64_x86_64-simulator/bctoolbox.framework/bctoolbox",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/belcard.xcframework/ios-arm64/belcard.framework/belcard",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/belcard.xcframework/ios-arm64/belcard.framework/belcard",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/belle-sip.xcframework/ios-arm64/belle-sip.framework/belle-sip",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/belle-sip.xcframework/ios-arm64/belle-sip.framework/belle-sip",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/belr.xcframework/ios-arm64/belr.framework/belr",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/belr.xcframework/ios-arm64/belr.framework/belr",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/lime.xcframework/ios-arm64/lime.framework/lime",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/lime.xcframework/ios-arm64/lime.framework/lime",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/linphone.xcframework/ios-arm64/linphone.framework/linphone",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/linphone.xcframework/ios-arm64/linphone.framework/linphone",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/linphonetester.xcframework/ios-arm64/linphonetester.framework/linphonetester",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/linphonetester.xcframework/ios-arm64/linphonetester.framework/linphonetester",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/mediastreamer2.xcframework/ios-arm64/mediastreamer2.framework/mediastreamer2",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/mediastreamer2.xcframework/ios-arm64/mediastreamer2.framework/mediastreamer2",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/msamr.xcframework/ios-arm64/msamr.framework/msamr",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/msamr.xcframework/ios-arm64/msamr.framework/msamr",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/mscodec2.xcframework/ios-arm64/mscodec2.framework/mscodec2",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/mscodec2.xcframework/ios-arm64/mscodec2.framework/mscodec2",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/msopenh264.xcframework/ios-arm64/msopenh264.framework/msopenh264",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/msopenh264.xcframework/ios-arm64/msopenh264.framework/msopenh264",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/mssilk.xcframework/ios-arm64/mssilk.framework/mssilk",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/mssilk.xcframework/ios-arm64/mssilk.framework/mssilk",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/mswebrtc.xcframework/ios-arm64/mswebrtc.framework/mswebrtc",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/mswebrtc.xcframework/ios-arm64/mswebrtc.framework/mswebrtc",
    "Pods/iOSPhoneLib/linphone-sdk-novideo-frameworks/ortp.xcframework/ios-arm64/ortp.framework/ortp",
    "Pods/linphone-sdk-novideo/linphone-sdk-novideo/apple-darwin/XCFrameworks/ortp.xcframework/ios-arm64/ortp.framework/ortp",
  ]

  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end
end
